name: VoiceFlow
options:
  bundleIdPrefix: com.voiceflow
  deploymentTarget:
    macOS: "26.0"
  xcodeVersion: "16.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "26.0"
    CODE_SIGN_IDENTITY: "-"
    CODE_SIGNING_REQUIRED: NO
    CODE_SIGN_ENTITLEMENTS: VoiceFlow/VoiceFlow.entitlements

targets:
  VoiceFlow:
    type: application
    platform: macOS
    sources:
      - path: VoiceFlow
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.voiceflow.app
        INFOPLIST_FILE: VoiceFlow/Info.plist
        PRODUCT_NAME: VoiceFlow
        GENERATE_INFOPLIST_FILE: NO
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        LD_RUNPATH_SEARCH_PATHS: "@executable_path/../Frameworks"
        ENABLE_HARDENED_RUNTIME: YES
    entitlements:
      path: VoiceFlow/VoiceFlow.entitlements
