name: Teleprompter
options:
  bundleId: com.teleprompter.app
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "13.0"

targets:
  Teleprompter:
    type: application
    platform: macOS
    sources:
      - path: Teleprompter
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.teleprompter.app
        INFOPLIST_FILE: Teleprompter/Info.plist
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: "-"
        PRODUCT_NAME: Teleprompter
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        COMBINE_HIDPI_IMAGES: YES
        ENABLE_HARDENED_RUNTIME: YES
        LD_RUNPATH_SEARCH_PATHS: "@executable_path/../Frameworks"
    entitlements:
      path: Teleprompter/Teleprompter.entitlements
